spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_jpa?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 12345678
      allow-pool-suspension: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true

